### ISSUE TITLE
Mod Request: Fat Experience Orbs

### ISSUE THREAD

**Issue by mr-pi12** [zorroware/fabric-optimization-mods#41]
**Requirements for a mod to be added:**
1. The mod must be open-source.
2. The mod cannot sacrifice vanilla behavior for performance.
3. The mod must be actively maintained.

**Mod name:** (mod name here)

**Type of mod (e.g. rendering, lighting, extra):** Rendering

**Repository (e.g. GitHub, GitLab, Gitea):** https://github.com/NinjaPhenix/FatExperienceOrbs

**Developer/organization:** NinjaPhenix

**Additional notes:**
Merges xp orbs into one entity, not as aggressively as clumps.

As of now, does not merge every single xp orb into a single entity.

**Comment by DragonEggBedrockBreaking** [comment]
@ReperakPro If it were up to me, I would allow this, simply because Mojang did a partial (but not perfect because Mojank) implementation of this in 1.17.

**Comment by ReperakPro** [comment]
This is an iffy choice. Although Mojang has done this in 1.17, this doesn't automatically mean modifying vanilla mechanics is good to go.

**Comment by DragonEggBedrockBreaking** [comment]
I feel like this is a loose extension - if cull leaves was accepted, I think this should be too. This rly helps in mass xp farms, like [gnembon's enderman farm](https://www.youtube.com/watch?v=ckhe8ws-a4w).

**Comment by ReperakPro** [comment]
Is this a purely visual change?

**Comment by mr-pi12** [comment]
> Is this a purely visual change?

No, like I said, it merges the entities into one, so you don't lag while picking up hundreds of xp orbs. In vanilla minecraft, it used to be that you would get massive fps drops as you collected many xp orbs. It works server side, but I don't know if it's client side.

**Comment by ReperakPro** [comment]
If this changes the mechanics/behavior of the XP orbs then this will not be included.

**Comment by mr-pi12** [comment]
I see why you do'nt want to add the mod, but I still like the performance benefits users can get out of it, especially from xp farms and things like that.

**Comment by DragonEggBedrockBreaking** [comment]
> If this changes the mechanics/behavior of the XP orbs then this will not be included.

Well in terms of user experience, there is no difference. When you get xp from an xp source, you will get the same amount of xp. The only reason something needs to happen on the server is for the server to know where the visual xp balls are.

**Comment by ReperakPro** [comment]
If the positions of the XP orbs are modified, then it will not be allowed.
