### ISSUE TITLE
Mod Request: MCMT for Fabric

### ISSUE THREAD

**Issue by mr-pi12** [zorroware/fabric-optimization-mods#44]
**Requirements for a mod to be added:**
1. The mod must be open-source.
2. The mod cannot sacrifice vanilla behavior for performance.
3. The mod must be actively maintained.

**Mod name:** MCMT for Fabric

**Type of mod (e.g. rendering, lighting, extra):** threading,

**Repository (e.g. GitHub, GitLab, Gitea):** https://github.com/himekifee/MCMTFabric/

**Developer/organization:** himekifee

**Additional notes:**
The mod requires Java 8, but a 1.17 version with support for Java 16 has been made as a pre-release. When using this mod, I found it to be partly stable on my pc, but it seems that in future, it might have improved compatibility and performance. This mod is based on the MCMT forge mod.

**Comment by ReperakPro** [comment]
From the description of the original mod:

> This fecks around with a LOT of minecraft's internal processing loops. If you are using this with any other mods; it may break. If you do something in vanilla, it might still break. It might break simply by you looking at it. It is almost impossible to test every possible interaction that CAN occur; all I can say is that it's worked in every case I've tested.

**Comment by mr-pi12** [comment]
I must have read over that, but then again, when I tested it on a new Minecraft instance, so I didn't notice mod incompatibilities due to the fact that I didn't use any other mods with it. Still, I find it quite interesting and I like the concept of this mod.
